name: Build ARM Docker images

on:
  push:
    branches:
      - docker  # todo: master
    paths:
      - 'arm/**'
      - '.github/workflows/build-docker.yml'

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker login
        run: |
          docker login -p ${{secrets.DOCKER_PASSWORD}} -u ${{secrets.DOCKER_USERNAME}}
      - name: Build docker image
        run: |
          docker build arm -t "trassiross/conan-arm" --build-arg "profile_name=hi3520dv300"
      - name: Upload docker image
        run: |
          docker push "trassiross/conan-arm"
